System.IO.Error: Fix a documentation link to Control.Exception.Exception
Instead of using double quotes (which are used to link to modules), use
single quotes (that are used to link, among others, to link to types,
which C.E.Exception is).

Signed-off-by: Austin Seipp <austin@well-typed.com>